/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package privatewhiteboard.client;

import java.rmi.RemoteException;
import java.util.Date;
import privatewhiteboard.shared.controllers.IClientController;
import privatewhiteboard.shared.interfaces.IChatBoard;
import javax.swing.*;

/**
 *
 * @author Sherry
 */
public class ChatBoardPanel extends JPanel implements IChatBoard 
{
    IClientController _clientController;
    /**
     * Creates new form ChatBoardPanel
     */
    public ChatBoardPanel() {
        initComponents();
    }
    
    public void Initialize(IClientController clientController)
    {
        _clientController=clientController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 600));
        setMinimumSize(new java.awt.Dimension(300, 600));
        setPreferredSize(new java.awt.Dimension(300, 600));

        jEditorPane1.setEditable(false);
        jEditorPane1.setMaximumSize(new java.awt.Dimension(280, 535));
        jEditorPane1.setMinimumSize(new java.awt.Dimension(280, 535));
        jEditorPane1.setPreferredSize(new java.awt.Dimension(280, 535));
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1);

        jPanel1.setMaximumSize(new java.awt.Dimension(280, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(280, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 40));

        jEditorPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));
        jEditorPane2.setAutoscrolls(false);
        jEditorPane2.setMaximumSize(new java.awt.Dimension(220, 30));
        jEditorPane2.setMinimumSize(new java.awt.Dimension(220, 30));
        jEditorPane2.setPreferredSize(new java.awt.Dimension(220, 30));
        jScrollPane2.setViewportView(jEditorPane2);

        jPanel1.add(jScrollPane2);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\SherryWon\\HOC KI 7 UIT\\XU LY PHAN BO\\Do an 2014-2015\\MAIN\\PrivateWhiteBoard.Client\\Images\\btnFace.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("labelEmo");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\SherryWon\\HOC KI 7 UIT\\XU LY PHAN BO\\Do an 2014-2015\\MAIN\\PrivateWhiteBoard.Client\\Images\\btnImage.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("labelImage");

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void PostMessage(int messageId, String senderName, Date sentTime, String messageContent) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void PostEmotion(int messageId, String senderName, Date sentTime, String emotionId) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
